package kg.devcats.processflow.model

object ButtonIds {
    const val EXIT_NAVIGATE_TO_WALLET_MAIN = "EXIT_NAVIGATE_TO_WALLET_MAIN"
    const val RETURN_TO_QUEUE_LATER = "RETURN_TO_QUEUE_LATER"
    const val SELFIE_PHOTO = "SELFIE_PHOTO"
    const val PASSPORT_FRONT_PHOTO = "PASSPORT_FRONT_PHOTO"
    const val PASSPORT_BACK_PHOTO = "PASSPORT_BACK_PHOTO"
    const val VIDEO_IDENT_BUTTON = "VIDEO_IDENT_BUTTON"
}

object WebViewIds {
    const val WEB_VIEW_VIDEO_IDENT = "VIDEO_IDENT"
}

object ScreenKey {
    const val STATUS_INFO = "STATUS_INFO"
    const val VIDEO_CALL = "VIDEO_CALL"
    const val VIDEO_CALL_PROMO = "VIDEO_CALL_PROMO"
    const val INPUT_OTP = "INPUT_OTP"
    const val PASSPORT_FRONT_PHOTO = "PASSPORT_FRONT_PHOTO"
    const val PASSPORT_BACK_PHOTO = "PASSPORT_BACK_PHOTO"
    const val SELFIE_PHOTO = "SELFIE_PHOTO"
    const val INPUT_FORM = "INPUT_FORM"
    const val WEB_VIEW = "WEB_VIEW"
}

object ContentTypes {
    const val PASSPORT_FRONT_PHOTO = "PASSPORT_FRONT_PHOTO"
    const val PASSPORT_BACK_PHOTO = "PASSPORT_BACK_PHOTO"
    const val SELFIE_PHOTO = "SELFIE_PHOTO"
    const val RECOGNIZED_PASSPORT_DATA = "RECOGNIZED_PASSPORT_DATA"
    const val FOREIGN_PASSPORT_FRONT_PHOTO = "FOREIGN_PASSPORT_FRONT_PHOTO"
    const val INPUT_FORM_DATA = "INPUT_FORM_DATA"
    const val INPUT_FIELD_CONTENT = "INPUT_FIELD_CONTENT"
    const val WEB_VIEW_RESULT = "WEB_VIEW_RESULT"
}